// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.0";

// src/lib/mcp/tools/list-patients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-patients.ts
var list_patients_default = defineTool({
  name: "list_patients",
  title: "List patients",
  description: "List patients accessible to the signed-in clinic user. Optional search by name.",
  inputSchema: {
    search: z.string().optional().describe("Optional case-insensitive name substring."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("patients").select("id, name, email, phone, cpf, payment_link, created_at").order("name").limit(limit ?? 50);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-patient.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_patient_default = defineTool2({
  name: "get_patient",
  title: "Get patient",
  description: "Fetch full details for a single patient by id.",
  inputSchema: {
    id: z2.string().uuid().describe("Patient id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("patients").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Patient not found" }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { patient: data } };
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_appointments_default = defineTool3({
  name: "list_appointments",
  title: "List appointments",
  description: "List appointments in a date range. Dates are ISO 8601 timestamps.",
  inputSchema: {
    from: z3.string().describe("Start ISO timestamp (inclusive)."),
    to: z3.string().describe("End ISO timestamp (exclusive)."),
    patient_id: z3.string().uuid().optional().describe("Filter by patient id."),
    limit: z3.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, patient_id, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("appointments").select("id, patient_id, starts_at, ends_at, status, external_summary, is_vittude, is_block, block_reason, notes, source").gte("starts_at", from).lt("starts_at", to).order("starts_at").limit(limit ?? 200);
    if (patient_id) q = q.eq("patient_id", patient_id);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { appointments: data ?? [] } };
  }
});

// src/lib/mcp/tools/create-appointment.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z4 } from "npm:zod@^3.25.76";
var create_appointment_default = defineTool4({
  name: "create_appointment",
  title: "Create appointment",
  description: "Create a new appointment for a patient.",
  inputSchema: {
    patient_id: z4.string().uuid(),
    starts_at: z4.string().describe("ISO timestamp"),
    ends_at: z4.string().describe("ISO timestamp"),
    notes: z4.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ patient_id, starts_at, ends_at, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("appointments").insert({ patient_id, starts_at, ends_at, notes, created_by: ctx.getUserId(), status: "scheduled" }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { appointment: data } };
  }
});

// src/lib/mcp/tools/list-finance-entries.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_finance_entries_default = defineTool5({
  name: "list_finance_entries",
  title: "List finance entries",
  description: "List financial entries in a date range.",
  inputSchema: {
    from: z5.string().describe("Start date ISO (inclusive)."),
    to: z5.string().describe("End date ISO (exclusive)."),
    status: z5.string().optional().describe("Filter by status (e.g. pago, a_receber)."),
    limit: z5.number().int().min(1).max(500).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("finance_entries").select("*").gte("entry_date", from).lt("entry_date", to).order("entry_date", { ascending: false }).limit(limit ?? 200);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { entries: data ?? [] } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "fomqcuntjyffnnvtbixo";
var mcp_default = defineMcp({
  name: "clinica-mcp",
  title: "Cl\xEDnica \u2014 Agendamento MCP",
  version: "0.1.0",
  instructions: "Ferramentas para gerenciar pacientes, agendamentos e financeiro da cl\xEDnica. Use list_patients para buscar pacientes, list_appointments para consultar a agenda, create_appointment para agendar, e list_finance_entries para consultar o financeiro. Todas as a\xE7\xF5es respeitam as permiss\xF5es do usu\xE1rio autenticado.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_patients_default, get_patient_default, list_appointments_default, create_appointment_default, list_finance_entries_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
